name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # v3 → v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4 # v3 → v4
        with:
          distribution: temurin     # 'adopt' → 'temurin' (AdoptOpenJDK is deprecated)
          java-version: '11'

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Run Security Scan
        run: |
          mkdir -p report
          curl -sSLo dc.zip https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip -q dc.zip
          chmod +x dependency-check/bin/dependency-check.sh
          ./dependency-check/bin/dependency-check.sh \
            --project JavaSecurityCheck \
            --scan ./ \
            --format HTML \
            --out report \
            --disableAssembly

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report/**             # ensure files inside folder are uploaded
          if-no-files-found: error
